apiVersion: apps/v1

kind: Deployment

metadata:
  name: spring-boot-configmap-deployment

  labels:
    app: spring-boot-configmap

spec:
  replicas: 3

  selector:
    matchLabels:
      app: spring-boot-configmap

  template:
    metadata:
      labels:
        app: spring-boot-configmap

    spec:
      containers:
        - name: spring-boot-configmap

          image: iamgovindthakur/spring-boot-configmap:latest
          env:
            - name: USER_NAME
              value: "GOVIND KUMAR THAKUR"

          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-configmap-service
spec:
  type: NodePort
  selector:
    app: spring-boot-configmap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
